export const PRODUCT_LIST = "PRODUCT_LIST"
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST"
export const CATEGORY_LIST = "CATEGORY_LIST"
export const LIKE_PRODUCT = "LIKE_PRODUCT"
export const DISLIKE_PRODUCT = "DISLIKE_PRODUCT"

